# Generated by Django 5.0.6 on 2024-05-08 11:07

from django.db import migrations, models

def add_admin_user(apps, schema_editor):
    Users = apps.get_model("attendance", "Users")
    Users.objects.create(
        type=0, full_name="AMS-Admin", username="admin_ams_nuage", email="admin-nuage@gmail.com"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_admin_user),
    ]
