# Generated by Django 5.0.6 on 2024-05-08 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20240508_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_submitted', to='attendance.users'),
        ),
    ]
